In [4]:
# 直接使用numpy创建的数据，实例如下：
import numpy as np
import pandas as pd

data = np.random.randn(5,4)- 1  # 创建一个5行4列的数据
print(data)

print('')  # 相当于换行的作用

df = pd.DataFrame(data)   # 给创建好的数据建立表格
print(df)

print(np.abs(df))   # 求数据的绝对值

[[-0.74880633  0.39325959 -0.26790867 -2.01997125]
 [ 0.26053765 -1.11743577 -0.04756093 -0.44547267]
 [-0.41489928  0.06558372 -1.71178063 -0.26003424]
 [-1.56180248 -1.03382329 -1.08701685  0.71981087]
 [-3.56395869 -1.11804491  0.50581787  0.71281892]]

          0         1         2         3
0 -0.748806  0.393260 -0.267909 -2.019971
1  0.260538 -1.117436 -0.047561 -0.445473
2 -0.414899  0.065584 -1.711781 -0.260034
3 -1.561802 -1.033823 -1.087017  0.719811
4 -3.563959 -1.118045  0.505818  0.712819
          0         1         2         3
0  0.748806  0.393260  0.267909  2.019971
1  0.260538  1.117436  0.047561  0.445473
2  0.414899  0.065584  1.711781  0.260034
3  1.561802  1.033823  1.087017  0.719811
4  3.563959  1.118045  0.505818  0.712819


In [8]:

df1 = pd.DataFrame(np.random.randint(2,4, size = (3,4)),
                   columns = list('abcd'),index = range(3))
print(df1)   #创建一个3行4列，列名为abcd，索引为0，1，2的表格

   a  b  c  d
0  2  2  3  2
1  3  3  3  3
2  3  3  2  2


In [9]:
# map 作用于series,不能用于dataframe，是元素级别的操作
df1['a'].map(lambda x: x**2)  # 对a列的数据做平方处理

0    4
1    9
2    9
Name: a, dtype: int64

In [16]:
# apply 作用于dataframe， 可以对行/列操作：
df2 = df1.apply(lambda x: x.max() - x.min(), axis = 0) 
print(df2) # lambda 标签代表处理的对象，axis=0 代表对列数据进行处理

df3 = df1.apply(lambda x: x.max() - x.min(), axis = 1)
print(df3) # lambda 标签代表处理的对象，axis=1 代表对列数据进行处理

a    1
b    1
c    1
d    1
dtype: int64
0    1
1    0
2    1
dtype: int64


In [17]:
# applymap 作用于整个dataframe元素
df4 = df1.applymap(lambda x: "old" if x%2==1 else "even")
print(df4)

      a     b     c     d
0  even  even   old  even
1   old   old   old   old
2   old   old  even  even


# 总结
在pandas中对元素操作有三种方式：map针对一列一列的数据，用于series的对象中，apply和applymap则在dataframe中使用，前者axis=0或1来表示对列或行的操作，后者直接对dataframe中的所有元素来操作。

In [24]:
# 1. 索引排序
# sort_index()

# 排序默认使用升序排序，ascending=False 为降序排序

# 对于series对象,索引为0-4的随机索引
s4 = pd.Series(range(10,15),index = np.random.randint(5, size = 5))
print(s4)

# 默认索引排序
s5 = s4.sort_index(ascending=False)  # 按照索引大小排序（降序）
print(s5)
print("="*30)
s6 = s4.sort_index()  # 按照索引大小排序（升序）
print(s6)

3    10
3    11
2    12
2    13
1    14
dtype: int64
3    10
3    11
2    12
2    13
1    14
dtype: int64
1    14
2    12
2    13
3    10
3    11
dtype: int64


In [31]:
# 对DataFrame进行索引操作时注意轴方向
# 
df7 = pd.DataFrame(np.random.randint(1,4, size =(5,4)), 
                  index = np.random.randint(4, size =5),  # 索引是随机数
                  columns = np.random.randint(4,size =4)) # 列标也是随机数
print(df7)
print('')

df7_isort = df7.sort_index(axis = 1, ascending = False)  # axis=1，对列进行降序操作
print(df7_isort)

print('')
df8_isort = df7.sort_index(axis = 0, ascending = False)  # axis=0，对行进行降序操作
print(df8_isort)

   1  3  2  1
3  1  1  2  3
1  1  3  1  1
3  3  3  1  2
2  1  1  2  1
2  2  2  3  3

   3  2  1  1
3  1  2  1  3
1  3  1  1  1
3  3  1  3  2
2  1  2  1  1
2  2  3  2  3

   1  3  2  1
3  1  1  2  3
3  3  3  1  2
2  1  1  2  1
2  2  2  3  3
1  1  3  1  1


In [34]:
# 2. 按值排序
# sort_values(by='column name')
# 根据某个唯一的列名进行排序，如果有其他相同列名则报错。

# 按值排序
df7_vsort = df7.sort_values(by=3, ascending=False) # 按照列索引为3的值来降序
print(df7_vsort)

   1  3  2  1
1  1  3  1  1
3  3  3  1  2
2  2  2  3  3
3  1  1  2  3
2  1  1  2  1


In [38]:
# 处理缺失数据(randn按照正态分布来产生4行3列随机数)
df_data = pd.DataFrame([np.random.randn(3),[1. ,2., np.nan],
                       [np.nan,4.,np.nan],[1., 2., 3.]])
print(df_data.head())

data1 = np.random.randn(10)
data1

          0         1         2
0 -0.302465 -1.323976 -1.923461
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000


array([ 0.64600512, -1.1927606 , -0.88649436,  1.73687643,  2.44530254,
       -0.43875143, -0.96518848,  1.80403373, -0.97329962,  0.07441172])

In [40]:
# 1. 判断是否存在缺失值：isnull()
# 判断df_data数据是否为空，空值就返回Ture，不为空就返回False
print(df_data.isnull())  

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


In [43]:
# 2. 丢弃缺失数据：dropna()函数
# 根据axis轴方向，丢弃包含NaN的行或列。 
print(df_data.dropna())   # 默认是行
print('='*30)

print(df_data.dropna(axis = 1))   # axis = 1将含有nan的列数据丢弃 

          0         1         2
0 -0.302465 -1.323976 -1.923461
3  1.000000  2.000000  3.000000
          1
0 -1.323976
1  2.000000
2  4.000000
3  2.000000


In [45]:
# 3. 填充缺失数据：fillna()，将nan 处的值都用fillna（）中的数据替换

print(df_data.fillna(-100.))     # 将nan的数据用-100替换


            0         1           2
0   -0.302465 -1.323976   -1.923461
1    1.000000  2.000000 -100.000000
2 -100.000000  4.000000 -100.000000
3    1.000000  2.000000    3.000000


# 总结
排序对series对象就使用 sort_index来根据索引排序，默认升序，ascending=False用来降序
对dataframe对象就要使用axis来决定是对行还是对列就行排序，axis=1对列排序；axis=0，对行排序
判断空值用isnull()函数即可，空值为Ture，值不为空则False
填充空值的位置直接用fillna()函数，括号里面的值就是用来替代空值
丢弃空值所在的行或者列用dropna()，axis = 0丢弃行，axis = 1丢弃列
还可以使用sort_values来根据值排序，只能选择列号唯一的列，不然会报错。by = 'columns name'