In [6]:
# 1.获取某行的数据（一维数组）
import numpy as np
a1 = np.arange(1, 29)
print(f"获取下表为1的元素a1[1]：{a1[1]}")

a2 = np.arange(1, 13).reshape((3, 4))

print(f"获取下表为1行的数据(a2[1]):{a2[1]}")


获取下表为1的元素a1[1]：2
获取下表为1行的数据(a2[1]):[5 6 7 8]


In [7]:
# 2.获取连续几行的数据
a1 = np.arange(0, 24).reshape((4,6))
print(a1)
print(a1[0:2])  #获取0行到1行的数据

# 1.获取不连续的几行数据
print(a1[[0, 2, 3]])

# 2.也可以用复数来索引
print(a1[[-1, -2]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[18 19 20 21 22 23]
 [12 13 14 15 16 17]]


In [9]:
# 3.获取某行某列的数据
a1 = np.arange(0,24).reshape((4,6))
print(a1[1,1]) # 获取1行1列的数据

# 获取0-1行0-1列的数据
print(a1[0:2,0:2])

# 获取（1，3）和（2，4）的两个数据，也叫花式索引
print(a1[[1,2], [3,4]])

7
[[0 1]
 [6 7]]
[ 9 16]


In [19]:
# 4.获取某列的数据
a1 = np.arange(0,24).reshape((4,6))
print(a1[:,1]) #获取第1列的数据


[ 1  7 13 19]


In [20]:
# 5.布尔索引（布尔索引运算是矢量的）
a1 = np.arange(0,24).reshape((4,6))
print(a1<10)#会返回一个新的数组，这个数组中的值全部都是bool类型



[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [23]:
# 6.提取列表中的数据
a1 = np.arange(0,24).reshape(4,6)
a2 = a1 < 10
#这样就会在a1中把a2中为True的元素对应的位置的值提取出来
print(a1[a2])

# 其中布尔运算可以有!=、==、>、<、>=、<=以及&(与)和|(或)。示例代码如下：
a1 = np.arange(0, 24).reshape((4, 6))
a2 = a1[(a1 < 5) | (a1 > 10)]
print(a2)

a3 = a1[(a1 >= 5) & (a1 <=  10)]
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 5  6  7  8  9 10]


In [30]:
# 7.利用索引进行值的替换
a1 = np.arange(0,24).reshape((4,6))
a1[1] = 0  #将第1行的所有值都替换成0
print(a1)

# 可以使用条件索引来实现
a1 = np.arange(0,24).reshape((4,6))#将小于5的所有值全部都替换成0
a1[a1 < 5] = 0
print(a1)

# where函数：
a1 = np.arange(0,24).reshape((4,6))
a2 = np.where(a1 < 10,1,0) #把a1中所有小于10的数全部变成1，其余的变成0
print(a2)

[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  0  0  0  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[1 1 1 1 1 1]
 [1 1 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


将np.arange(10)数组中的奇数全部都替换成-1。

有一个4行4列的数组（比如：np.random.randint(0,10,size=(4,4))），
请将其中对角线的数取出来形成一个一维数组。提示（使用np.eye）。

有一个4行4列的数组，请取出其中(0,0),(1,2),(3,2)的点。

有一个4行4列的数组，请取出其中2-3行（包括第3行）的所有数据。

有一个8行9列的数组，请将其中1-5行（包含第5行）的第8列大于3的数全部都取出来。

In [42]:
import numpy as np
a1 = np.arange(10)
a1[a1%2 != 0] = 0 
print(a1  )



[0 0 2 0 4 0 6 0 8 0]


In [40]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  