In [3]:
# 6拷贝：深拷贝和浅拷贝
# 6.1如果只是简单的赋值，那么不会进行拷贝。
import numpy as np
a = np.arange(12)
b = a#这种情况不会进行拷贝
print(b is a)#这种情况不会进行拷贝

True


In [5]:
"""6.2View或者浅拷贝：
   有些情况，会进行变量的拷贝，但是他们所指向的内存空间都是一样的，
   那么这种情况叫做浅拷贝，或者叫做View(视图)"""
a = np.arange(12)
c = a.view()
print(c is a)#返回False，说明c和a是两个不同的变量
c[0] = 100
print(c)
print(a[0])#打印100，说明对c上的改变，会影响a上面的值，说明他们指向的内存空间还是一样的，这种叫做浅拷贝，或者说是view

False
[100   1   2   3   4   5   6   7   8   9  10  11]
100


In [7]:
#6.3深拷贝：
#将之前数据完完整整的拷贝一份放到另外一块内存空间中，这样就是两个完全不同的值了。
a = np.arange(12)
d = a.copy()
print(a)
print(d is a)#返回False，说明d和a是两个不同的变量
d[0] = 100
print(d)
print(a[0])#打印0，说明d和a指向的内存空间完全不同了。

[ 0  1  2  3  4  5  6  7  8  9 10 11]
False
[100   1   2   3   4   5   6   7   8   9  10  11]
0
