NAN和INF值处理：
首先我们要知道这两个英文单词代表的什么意思：
NAN：Not A number，不是一个数字的意思，但是他是属于浮点类型的，
所以想要进行数据操作的时候需要注意他的类型。
INF：Infinity，代表的是无穷大的意思，也是属于浮点类型。
np.inf表示正无穷大，-np.inf表示负无穷大，一般在出现除数为0的时候为无穷大。比如2/0。

NAN一些特点：
NAN和NAN不相等。比如np.NAN != np.NAN这个条件是成立的。
NAN和任何值做运算，结果都是NAN。
有些时候，特别是从文件中读取数据的时候，经常会出现一些缺失值。缺失值的出现会影响数据的处理。因此我们在做数据分析之前，先要对缺失值进行一些处理。处理的方式有多种，需要根据实际情况来做。一般有两种处理方式：删除缺失值，用其他值进行填充。

In [4]:
"""NAN一些特点：
NAN和NAN不相等。比如np.NAN != np.NAN这个条件是成立的。
NAN和任何值做运算，结果都是NAN。
有些时候，特别是从文件中读取数据的时候，经常会出现一些缺失值。
缺失值的出现会影响数据的处理。因此我们在做数据分析之前，
先要对缺失值进行一些处理。处理的方式有多种，需要根据实际情况来做。
一般有两种处理方式：删除缺失值，用其他值进行填充。
"""
# 8.1. 删除所有NAN的值，因为删除了值后数组将不知道该怎么变化，所以会被变成一维数组
import numpy as np
data = np.random.randint(0,10,size=(3,5)).astype(np.float)
print(data)
data[0,1] = np.nan
data = data[~np.isnan(data)] # 此时的data会没有nan，并且变成一个1维数组
data

[[2. 0. 5. 2. 6.]
 [5. 1. 4. 5. 7.]
 [0. 8. 6. 3. 6.]]


array([2., 5., 2., 6., 5., 1., 4., 5., 7., 0., 8., 6., 3., 6.])

In [6]:
# 8.2 删除nan所在的行
data = np.random.randint(0,10, size = (3, 5)).astype(np.float)
print(data)
# 将第（0，1）和（1，2）两个值设为NAN
data[[0,1],[1,2]] = np.NAN
print(data)
# 获取哪些行有NAN
lines = np.where(np.isnan(data))[0]
print(lines)
# 使用delete方法删除指定的行,axis=0表示删除行，lines表示删除的行号
data1 = np.delete(data,lines,axis=0)
print(data1)

[[2. 0. 6. 3. 2.]
 [0. 3. 4. 2. 2.]
 [7. 6. 8. 2. 2.]]
[[ 2. nan  6.  3.  2.]
 [ 0.  3. nan  2.  2.]
 [ 7.  6.  8.  2.  2.]]
[0 1]
[[7. 6. 8. 2. 2.]]
