In [3]:
# np.random模块
# 1.1 np.random.seed用于指定随机数生成时所用算法开始的整数值，如果使用相同
# 的seed()值，则每次生成的随即数都相同，如果不设置这个值，则系统根据时间来自
# 己选择这个值，此时每次生成的随机数因时间差异而不同。一般没有特殊要求不用设置。
import numpy as np
np.random.seed(1)
print(np.random.rand())# 打印0.417022004702574
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())# 打印其他的值，因为随机数种子只对下一次随机数的产生会有影响。

0.417022004702574
0.7203244934421581
0.00011437481734488664
0.30233257263183977


In [5]:
# 1.2np.random.rand生成一个值为[0,1)之间的数组，形状由参数指定，如果没有参数，
#那么将返回一个随机值。
data1 = np.random.rand(2,3,4)# 生成2块3行4列的数组，值从0-1之间
print(data1)
data2 = np.random.rand()#生成一个0-1之间的随机数
print(data2)

[[[0.8781425  0.09834683 0.42110763 0.95788953]
  [0.53316528 0.69187711 0.31551563 0.68650093]
  [0.83462567 0.01828828 0.75014431 0.98886109]]

 [[0.74816565 0.28044399 0.78927933 0.10322601]
  [0.44789353 0.9085955  0.29361415 0.28777534]
  [0.13002857 0.01936696 0.67883553 0.21162812]]]
0.2655466593722262


In [6]:
# 1.3 np.random.randn生成均值(μ)为0，标准差（σ）为1的标准正态分布的值。
data3 = np.random.randn(2,3) #生成一个2行3列的数组，数组中的值都满足标准正太分布
print(data3)

[[-0.67124613 -0.0126646  -1.11731035]
 [ 0.2344157   1.65980218  0.74204416]]


In [12]:
# 1.4np.random.choice从一个列表或者数组中，随机进行采样。或者是从指定的区间
# 中进行采样，采样个数可以通过参数指定
data = [4,65,6,7,9,34,73,8]
result1 = np.random.choice(data, size = (2,3))#从data中随机采样，生成2行3列的数组
print(result1)
result2 = np.random.choice(data, 3)#从data中随机采样3个数据形成一个一维数组
print(result2)
result3 = np.random.choice(10,3)#从0-10之间随机取3个值
print(result3)

[[ 9 65 73]
 [ 9 65  4]]
[ 6  7 65]
[2 7 2]


In [23]:
# 1.5 np.random.shuffle把原来数组的元素的位置打乱。
a = np.arange(10)
print(a)
np.random.shuffle(a)#将a的元素的位置都会进行随机更换
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 7 0 6 4 2 1 3 9 8]
