轴（Axis）:每个线性数组都有一个轴，轴即数组的维度。

秩（rank）：秩描述数组的维数，即轴的数量；一维数组的秩为1，二维数组的秩为2.

在使用时候声明axis,axis=0对列操作，axis=1对行操作

In [1]:
import numpy  as np
x = np.array([[1,2,3],[4,5,6]])
print(x)
# 按列进行求和
print(x.sum(axis=0))
# 按行求和
print(x.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


常见的ndarray的属性
ndarray.ndim   秩，轴的数量
ndarray.size   数组元素的总个数
ndarray.shape  数组的维度
ndarray.dtype  数组元素的类型
ndaaray.itemsize   每个元素的大小（B）
ndarray.data   实际的数组元素

In [5]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print('x.size:', x.size)
print('x.dtype:', x.dtype)
print('x.itemsize:', x.itemsize)
print('x.data:', x.data)
print('x.ndim:', x.ndim)
print('x.shape:', x.shape)

x.size: 6
x.dtype: int32
x.itemsize: 4
x.data: <memory at 0x000002EE1B39D5F0>
x.ndim: 2
x.shape: (2, 3)
