In [9]:
import numpy as np

a1 = np.random.randint(-5,5, size = (1,20))
print(f"a1 为：{a1}")

a2 = np.sum(a1)#求出数组的和
print(f"a1 的和为：{a2}")

a3 = np.abs(a1) # 将a1数组的值全部求其绝对值
print(f"a1 的绝对值为：{a3}")

a4 = np.square(a1) # 求数组的平方
print(f"a1 的平方为：{a4}")

a5 = np.prod(a1) # 计算a1的乘积
print(f"a1 的乘积为：{a5}")

a6 = np.mean(a1) # 计算a1元素的平均值
print(f"a1 的平均值为：{a6}")

a7 = np.std(a1) # 计算元素的标准差
print(f"a1 的标准差为：{a7}")

a8 = np.var(a1) # 计算元素的方差
print(f"a1 的方差为：{a8}")

a9 = np.min(a1) # 计算元素的最小值
print(f"a1 的最小值为:{a9}")

a10 = np.max(a1) # 计算元素的最大值
print(f"a1 的最大值为:{a10}")

a11 = np.argmin(a1) # 找出最小值的索引
print(f"a1 最小值的索引为：{a11}")

a12 = np.argmax(a1) # 找出元素最大值的索引
print(f"a1 最大值的索引为：{a12}")

a13 = np.median(a1) #计算元素的中位数
print(f"a1 的中位数为：{a13}")

a1 为：[[-2  4 -5  0  1  0  2 -3 -4 -5 -3  4 -1  2  4 -3 -3 -1  4 -2]]
a1 的和为：-11
a1 的绝对值为：[[2 4 5 0 1 0 2 3 4 5 3 4 1 2 4 3 3 1 4 2]]
a1 的平方为：[[ 4 16 25  0  1  0  4  9 16 25  9 16  1  4 16  9  9  1 16  4]]
a1 的乘积为：0
a1 的平均值为：-0.55
a1 的标准差为：2.9912372022292044
a1 的方差为：8.947499999999998
a1 的最小值为:-5
a1 的最大值为:4
a1 最小值的索引为：2
a1 最大值的索引为：1
a1 的中位数为：-1.0


In [14]:
"""np.random.rand(d0,d1,d2……dn) 
注：使用方法与np.random.randn()函数相同 
作用： 
通过本函数可以返回一个或一组服从“0~1”均匀分布的随机样本值。随机样本取值范围是
[0,1)，不包括1。 
应用：在深度学习的Dropout正则化方法中，可以用于生成dropout随机向量（dl），例如
（keep_prob表示保留神经元的比例）：dl = np.random.rand(al.shape[0],al.shape[1]) < keep_prob
"""

# 使用np.sum或者是a.sum即可实现。并且在使用的时候，可以指定具体哪个轴。
# 同样Python中也内置了sum函数，但是Python内置的sum函数执行效率没有np.sum
# 那么高,可测试：
a = np.random.rand(1000000)
%timeit sum(a) #使用Python内置的sum函数求总和，看下所花费的时间
%timeit np.sum(a) #使用Numpy的sum函数求和，看下所花费的时间


140 ms ± 24.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.54 ms ± 33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
# np.any	验证任何一个元素是否为真
# np.all	验证所有元素是否为真
a1 = np.array([1,-2,0,1,2])
print(np.all(a1==0))#数组中是不是所有元素都为0
print((a1==0).all())

print(np.any(a1==0))#看数组中是否有等于0的数
print((a1==0).any())

False
False
True
True


In [27]:
help (np.any)

Help on function any in module numpy.core.fromnumeric:

any(a, axis=None, out=None, keepdims=<no value>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (`axis` = `None`) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the e

In [34]:
# np.sort：指定轴进行排序。默认是使用数组的最后一个轴进行排序。
a = np.random.randint(0,10, size = (3,5))
print(a)
b = np.sort(a) #按照行进行排序，因为最后一个轴是1，那么就是将最里面的元素进行排序。
print(b)
c = np.sort(a, axis = 0) # 按照列进行排序，因为指定了axis=0
print(c)
d = np.sort(a, axis = 1) #按照行进行排序，因为指定了axis=1
print(d)
print("="*30)
# ndarray.sort()，这个方法会直接影响到原来的数组，而不是返回一个新的排序后的数组。
a1 = np.random.randint(0,10, size = (3,5))
print(a1)
np.ndarray.sort(a1)
a1

[[5 6 1 0 6]
 [5 6 1 8 2]
 [4 7 3 8 5]]
[[0 1 5 6 6]
 [1 2 5 6 8]
 [3 4 5 7 8]]
[[4 6 1 0 2]
 [5 6 1 8 5]
 [5 7 3 8 6]]
[[0 1 5 6 6]
 [1 2 5 6 8]
 [3 4 5 7 8]]
[[2 9 6 0 9]
 [9 9 3 0 9]
 [9 0 4 5 1]]


array([[0, 2, 6, 9, 9],
       [0, 3, 9, 9, 9],
       [0, 1, 4, 5, 9]])

In [37]:
# np.argsort：返回排序后的下标值。
a = np.random.randint(0,10, size = (3,5))
print(a)
a1 = np.argsort(a) #默认也是使用最后的一个轴来进行排序。
print(a1)

[[9 5 8 4 5]
 [5 2 1 2 5]
 [4 6 3 8 5]]
[[3 1 4 2 0]
 [2 1 3 0 4]
 [2 0 4 1 3]]


In [41]:
# 降序排序：np.sort默认会采用升序排序。如果我们想采用降序排序。
a = np.random.randint(0,10, size = (3,5))
print(a)
# 1. 使用负号
a2 = -np.sort(-a)
print(a2)

# 2. 使用sort和argsort以及take
indexes = np.argsort(-a) #排序后的结果就是降序的
print(indexes)
a4 = np.take(a,indexes) #从a中根据下标提取相应的元素
print(a4)

[[2 3 7 0 7]
 [0 6 6 4 0]
 [0 0 1 5 1]]
[[7 7 3 2 0]
 [6 6 4 0 0]
 [5 1 1 0 0]]
[[2 4 1 0 3]
 [1 2 3 0 4]
 [3 2 4 0 1]]
[[7 7 3 2 0]
 [3 7 0 2 7]
 [0 7 7 2 3]]


In [45]:
# np.apply_along_axis：沿着某个轴执行指定的函数。
a = np.random.randint(0,10, size = (3,5))
print(a)
# 求数组a按行求均值，并且要去掉最大值和最小值。

a4 = np.apply_along_axis(lambda x:x[(x != x.max()) & (x != x.min())].mean(),axis=1,arr=a)
print(a4)

[[8 2 6 9 9]
 [9 0 7 7 3]
 [5 9 5 5 8]]
[7.         5.66666667 8.        ]


In [48]:
# np.linspace：用来将指定区间内的值平均分成多少份。
# 将0-10分成12分，生成一个数组
a = np.linspace(0,10,10)
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [49]:
# np.unique：返回数组中的唯一值。
a = np.array([1,2,3,3,2,4,4,])
# 返回数组a中的唯一值，并且会返回每个唯一值出现的次数。
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([1, 2, 2, 2], dtype=int64))